// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMdv7lUpXiabXT5_mZIwVr-OA9HqkJ1ok',
    appId: '1:194370004351:web:38910ca1a913676a93664a',
    messagingSenderId: '194370004351',
    projectId: 'bookdatabase111',
    authDomain: 'bookdatabase111.firebaseapp.com',
    storageBucket: 'bookdatabase111.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZ6ojBRG2x9uXF9-hpyWFzoREGNkC2ZsE',
    appId: '1:194370004351:android:f4e5e3afb51dba8993664a',
    messagingSenderId: '194370004351',
    projectId: 'bookdatabase111',
    storageBucket: 'bookdatabase111.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAK8fm2x_0oU4PwQu2OLdD_4vjSWSxvjmc',
    appId: '1:194370004351:ios:a99a6beda4f2d6cb93664a',
    messagingSenderId: '194370004351',
    projectId: 'bookdatabase111',
    storageBucket: 'bookdatabase111.firebasestorage.app',
    iosBundleId: 'com.example.bookreaderapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAK8fm2x_0oU4PwQu2OLdD_4vjSWSxvjmc',
    appId: '1:194370004351:ios:a99a6beda4f2d6cb93664a',
    messagingSenderId: '194370004351',
    projectId: 'bookdatabase111',
    storageBucket: 'bookdatabase111.firebasestorage.app',
    iosBundleId: 'com.example.bookreaderapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMdv7lUpXiabXT5_mZIwVr-OA9HqkJ1ok',
    appId: '1:194370004351:web:fd105ed3dc2c7db193664a',
    messagingSenderId: '194370004351',
    projectId: 'bookdatabase111',
    authDomain: 'bookdatabase111.firebaseapp.com',
    storageBucket: 'bookdatabase111.firebasestorage.app',
  );
}
